gg.jte.development-mode=true
spring.application.name=Avto

spring.datasource.url=jdbc:postgresql://localhost/Autos
spring.datasource.username=postgres
spring.datasource.password=I1wtbacp!
spring.datasource.driver-class-name=org.postgresql.Driver
spring.security.user.name=admin
spring.security.user.password=1234

spring.jpa.hibernate.ddl-auto=none

